#-*- coding:utf-8 -*-

KEY_ACTION_LIST = "KEY_ACTION_LIST"

KEY_ACTION_TASK_LIST = "KEY_ACTION_TASK_LIST"

ACTION_SIGN = 1
ACTION_LOGIN = 2
ACTION_PLAY = 3

ACTION_MAPPING = {
    ACTION_SIGN:[KEY_ACTION_TASK_LIST],
    ACTION_LOGIN:[KEY_ACTION_TASK_LIST],
}